spring:
  datasource:
    url: jdbc:mysql://localhost:3316/lotto_purchase
    username: lotto_user
    password: lotto1234
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 7001

services:
  draw-service:
    url: http://localhost:7002

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
