spring:
  datasource:
    url: jdbc:mysql://localhost:3317/lotto_draw
    username: lotto_user
    password: lotto1234
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 7002

services:
  result-service:
    url: http://localhost:7003