spring:
  datasource:
    url: jdbc:mysql://localhost:3318/lotto_result
    username: lotto_user
    password: lotto1234
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 7003

services:
  draw-service:
    url: http://localhost:7002
  purchase-service:
    url: http://localhost:7001

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/